;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-backward-word-begin
        evil-delete
        evil-inner-tag
        evil-normal-state
        ))

(setq mc/cmds-to-run-once
      '(
        evil-a-tag
        evil-delete-backward-char-and-join
        evil-find-char-to
        evil-forward-word-begin
        evil-insert
        ))
